import { Request, Response } from 'express';
import { PrismaClient } from '@prisma/client';
import fileService from '../services/fileService';

const prisma = new PrismaClient();

// Groups
export const getGroups = async (req: Request, res: Response) => {
  try {
    const groups = await prisma.squadGroup.findMany({
      include: {
        _count: {
          select: { admins: true }
        }
      }
    });
    res.json(groups);
  } catch (error) {
    res.status(500).json({ error: 'Failed to fetch groups' });
  }
};

export const createGroup = async (req: Request, res: Response) => {
  const { name, permissions } = req.body;
  try {
    const group = await prisma.squadGroup.create({
      data: { name, permissions }
    });
    res.status(201).json(group);
  } catch (error) {
    res.status(500).json({ error: 'Failed to create group' });
  }
};

export const updateGroup = async (req: Request, res: Response) => {
  const id = req.params.id as string;
  const { name, permissions } = req.body;
  try {
    const group = await prisma.squadGroup.update({
      where: { id },
      data: { name, permissions }
    });
    res.json(group);
  } catch (error) {
    res.status(500).json({ error: 'Failed to update group' });
  }
};

export const deleteGroup = async (req: Request, res: Response) => {
  const id = req.params.id as string;
  try {
    await prisma.squadGroup.delete({ where: { id } });
    res.status(204).send();
  } catch (error) {
    res.status(500).json({ error: 'Failed to delete group' });
  }
};

// Admins
export const getAdmins = async (req: Request, res: Response) => {
  try {
    const admins = await prisma.squadAdmin.findMany({
      include: { group: true }
    });
    res.json(admins);
  } catch (error) {
    res.status(500).json({ error: 'Failed to fetch admins' });
  }
};

export const addAdmin = async (req: Request, res: Response) => {
  const { steamId, name, groupId } = req.body;
  try {
    const admin = await prisma.squadAdmin.create({
      data: { steamId, name, groupId }
    });
    res.status(201).json(admin);
  } catch (error) {
    res.status(500).json({ error: 'Failed to add admin' });
  }
};

export const deleteAdmin = async (req: Request, res: Response) => {
  const id = req.params.id as string;
  try {
    await prisma.squadAdmin.delete({ where: { id } });
    res.status(204).send();
  } catch (error) {
    res.status(500).json({ error: 'Failed to delete admin' });
  }
};

// Generate Config
export const generateConfig = async (req: Request, res: Response) => {
  try {
    const groups = await prisma.squadGroup.findMany();
    const admins = await prisma.squadAdmin.findMany({
      include: { group: true }
    });

    let config = '// Squad Admins.cfg generated by SQFY Panel\n\n';
    
    // Write Groups
    config += '// Groups\n';
    groups.forEach(g => {
      config += `Group=${g.name}:${g.permissions}\n`;
    });

    config += '\n// Admins\n';
    admins.forEach(a => {
      // Format: Admin=SteamID:GroupName // Optional comment
      config += `Admin=${a.steamId}:${a.group.name} // ${a.name || 'No Name'}\n`;
    });

    res.json({ config });
  } catch (error) {
    res.status(500).json({ error: 'Failed to generate config' });
  }
};

// Sync Config
export const syncConfig = async (req: Request, res: Response) => {
  const { serverId } = req.body;
  try {
    const server = await prisma.server.findUnique({ where: { id: serverId } });
    if (!server) return res.status(404).json({ error: 'Server not found' });

    // Reuse config generation logic
    const groups = await prisma.squadGroup.findMany();
    const admins = await prisma.squadAdmin.findMany({ include: { group: true } });
    
    // Fetch whitelist entries for this server
    const whitelist = await prisma.whitelist.findMany({
      where: { serverId },
      include: { player: true }
    });

    let config = '// Squad Admins.cfg generated by SQFY Panel\n\n';
    config += '// Groups\n';
    groups.forEach(g => {
      config += `Group=${g.name}:${g.permissions}\n`;
    });
    
    // Add virtual VIP group if whitelist exists
    if (whitelist.length > 0) {
      config += 'Group=VIP:Reserved // Generated for VIPs\n';
    }

    config += '\n// Admins\n';
    admins.forEach(a => {
      config += `Admin=${a.steamId}:${a.group.name} // ${a.name || 'No Name'}\n`;
    });
    
    // Add Whitelisted players as VIPs
    whitelist.forEach(w => {
      // Check expiration
      if (w.expiresAt && new Date(w.expiresAt) < new Date()) {
        // Expired, skip (and maybe should be cleaned up by a cron job)
        return;
      }
      
      let name = 'VIP';
      try {
        const history = JSON.parse(w.player.nameHistory);
        if (history.length > 0) name = history[history.length - 1];
      } catch (e) {}
      
      config += `Admin=${w.steamId}:VIP // ${name} (Expires: ${w.expiresAt ? w.expiresAt.toISOString().split('T')[0] : 'Never'})\n`;
    });

    await fileService.writeFile(server, 'Admins.cfg', config);
    res.json({ message: 'Config synced successfully' });
  } catch (error: any) {
    console.error('Sync failed:', error);
    res.status(500).json({ error: 'Failed to sync config', details: error.message });
  }
};
